baseURL: /
languageCode: en-us
title: The COVID Watch Program
theme: hugo-fresh-mod

params:
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: COVID Watch
    # Hero subtitle (optional)
    subtitle: A Penn Medicine program that automatically checks in with patients at risk for complications of COVID-19 who are self-isolating at home
    # Button text Seamless enrollment. Remote Monitoring. Clinical Escalation
    buttontext: Learn More
    # Where the main hero button links to
    buttonlink: "#section7"
    # Hero video
    image: illustrations/icons/dailycheckin2.png
    # image placeholder for video (from /images/illustrations/icons/placeholder.png)
    #subtitle2: 
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Why COVID Watch
    url: /#section1
  - title: Eligibility
    url: /#section3  
  # - title: Program Features
  #   url: /#section4
  # - title: The Team
  #   url: /#section6
  - title: How To @ Penn
    url: /#section10
  section1:
    title: Why COVID Watch?
    subtitle: 
    tiles:
    - title: Support home isolation, prevent unnecessary exposure
      icon: person
      text: COVID-19 patients should self-isolate unless they need care — typically for hypoxemia.
      url: /
      buttonText: 
    - title: Automated daily check-ins with affected patients
      icon: multiply
      text: Check-in twice daily with patients to see how they are feeling and provide reassurance.
      url: /
      buttonText: 
    - title: Get patients the care they need at the right time
      icon: acogtiming_grey
      text: Quickly identify patients who need medical attention and escalate their care to a provider or Emergency Department. 
      url: /
      buttonText:
    title2: Our Approach
    subtitle2: 
    tiles2: 
    - title: Patient friendly
      icon: telemedicine
      text: COVID Watch is a simple text-based program that checks in to assess how patients are feeling and if they are having difficulty breathing.
      url: /
      buttonText: 
    - title: Provider friendly
      icon: doctor
      text: Providers across the health system, from primary care to ED to hospital medicine, can enroll patients in PennChart using Way to Health. No new logins needed.
      url: /
      buttonText:
    - title: Evaluate as needed
      icon: badge
      text: Clinical concerns are escalated immediately to Penn Medicine OnDemand nurses, physicians and APPs via PennChart. 
      url: /
      buttonText: 
  section3:
    title: Eligibility Criteria
    subtitle: Penn Medicine Guidelines
    tiles:
    - title: 
      icon: criteria2
      text1: 
      text2: 
      text3: 
      text4: Patient with Penn Medicine PCP
      text5: UP or UPHS employee using Penn Medicine On Demand
      text6: Patients who test positive through occupational health
      text7: Patients who test positive via tests ordered at by Penn clinicians (e.g., drive thru, ED)
      text8: Open to all Penn Medicine patients
      url: /
      buttonText:
  section10:
    title: COVID Watch 
    subtitle: FAQs for Providers
    summary: This is a PennMedicine home symptom monitoring program for patients who are self-isolating at home. It automatically checks in with enrolled COVID-19 positive or symptomatic patients twice a day for 14 days via SMS text. If a patient reports severe dyspnea during this time, they will be escalated to an RN pool. RN will triage to ED, urgent (within 1 hour) evaluation by on-call MD, or back to PCP (or PMOD if no PCP) for non-urgent evaluation.
    pathway: pathway2
    faqs:
    - question: Why should I refer my patients to COVID Watch?
      answer: With daily monitoring, COVID Watch can help quickly identify and facilitate escalations of patients with symptoms concerning for hypoxemia and/or severe pulmonary distress, while reducing ED volume of less concerning patients with mild symptoms who do not require hospitalization.
    - question: Who should I refer to COVID Watch?
      answer: Patients have tested COVID-19 positive (symptomatic or asymptomatic), are COVID-pending, or have significant respiratory symptoms concerning for COVID-19. In general, providers can refer to COVID Watch at the time when a test is ordered. Given the current low sensitivity of COVID testing, a negative test does not necessarily indicate true negative status.
    - question: Is this suitable for patients who need in-person evaluations?
      answer: COVID Watch is currently only available for home-dwelling patients with cell phones that can send and receive texts. If a patient is unable to text, needs home health care, or requires of pulse oximetry due to advanced lung or cardiac disease, they should be referred to Penn Medicine Home Health (via PennChart). Home care can evaluate the patient within 24-36 hrs, get vital signs, leave home monitoring equipment (e.g. pulse ox), and can follow-up with a more intensive home monitoring program.
    - question: Who responds to patient escalations?
      answer: If a patient reports that their breathing has become difficult through COVID Watch, an escalation notice is sent to a dedicated group of nurses within PennChart. The RN will call and triage patients within an hour of the escalation and refer them directly to an ED, for urgent follow-up with an appointment with Penn Medicine on Demand, or to their PCP for non-urgent follow-up. Patients without a usual source of care will be referred to Penn Medicine on Demand.  The RNs are backed up by an on call APP and MD for any urgent issues, day or night.  
    script:
    - heading: Enrollment Script
      instruction: >-
        - *We can enroll you into our “COVID Watch” program for the next 14 days. In this program we will help monitor your symptoms and assist you if your symptoms escalate. We will text you twice a day to quickly check in. If your symptoms make breathing difficult, a nurse or doctor will call you. If your symptoms get worse, you can also text to request a check-in. This service does not replace 911. If you ever reach a point where you feel you need to call 911, you should do so. Is this a program you would like to be a part of?*
        
        - **If YES, confirm patient has a cell phone**
        
        - Enroll patient into ​COVID Watch​ (steps to access Way to Health outlined below).

        - *Can you confirm XXX-XXX-XXXX is your cell phone, and that it can receive text messages?*

        - **If NO OR patient does not have a cell phone**
        
        - Patient cannot be enrolled into the COVID Watch program. Reinforce to patient that they should contact their PCP with non-urgent issues and call 911 if severe SOB or for emergencies.
      image:
    - heading: Please document every time you offer a patient COVID Watch using one PennChart SmartPhrase
      instruction: >-
        - Documentation of encounter is crucial to ensure accurate tracking of the program and reporting. <br/>
        
        - **.COVIDWATCHDECLINED**​ documents patient declining enrollment into the program. <br/>
        
        - **.COVIDWATCHENROLL**​ documents verbal agreement to be enrolled, and patient’s COVID status and current symptoms.
      image:
    - heading: How to enroll patients in COVID Watch in PennChart
      instruction: >- 
        From the patient chart, click “​More​” > “​Way to Health​”.   
      image: w2hlink
    - heading: Click the ​“Get Read Only Access”​ button
      instruction: >-
        Only needed if this is your first time accessing
      image: w2haccess
    - heading: In the list of programs shown, _​COVID-19 WATCH​ is the first one on the list. 
      instruction: >- 
        Click the “Enroll” button to start the patient in the program.
      image: w2henroll
    - heading: Verify the phone number & update if needed
      instruction: >- 
        - **This MUST be a cell phone number that accepts text messages**.
        
        - Note​ - Phone number pulled here is from PennChart, but updating the phone number within Way to Health ​will not ​update PennChart.

        - Ask patient if there is a Penn Medicine PCP or provider (i.e. specialist) who should be copied on updates while he/she is enrolled in COVID Watch. Fill in as needed. Enter N/A if none specified. 
        
        - Click the “Enroll” button. Upon enrollment, the patient will receive a welcome text message.
      image: w2hphone
  footer:
    # Logo (from /images/logos/___)
    logo: nc.svg
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://pennmedicine.org
      icon: pennmed.png
    - link: http://waytohealth.org/
      icon: waytohealth2.png      
    - link: https://healthcareinnovation.upenn.edu/
      icon: hcilogo3.png
    # **********  IGNORE OR NOT USED below this line ********************************************
  section4: 
    title: Program Features
    subtitle: Simple. Embedded. No downloads. No logins.
    icon1: patient
    icon2: provider
    tiles:
    - title: Text based
      text: Non aliquam in ducimus et ipsam a voluptas vel dolor. Et nostrum quis quos enim magni aut ab et. Numquam eaque non natus delectus ut error. Ut molestiae culpa ut tenetur libero officia consequuntur.
    - title: Efficient automation
      text:  Pxx
    - title: Real-world expertise
      text: Txx
    - title: Continual innovation
      text: xx
  section5:
    title: Contact us for a demo
    subtitle: ICYMI
    image: illustrations/mockups/mockup2-min.png
    buttonText: 
    buttonLink: "#"
  section6:
    title: The Team
    subtitle: xx
    clients:
    - name: xx
      quote: 
      job: xx
      img: xx
      link: xx
    - name: xx
      quote: 
      job: xx
      img: xx
      link: xx
  section2:
    title: Awards
    subtitle: Multiple national and innovation awards
    features:
    - title: 
      text: 
      icon: aha2
    - title: 
      text: 
      icon: aheart2
    - title: 
      text: 
      icon: council2
    features2:
    - title: 
      text: 
      icon: vizient2
    - title: 
      text: 
      icon: pbj      
  sidebar:
    # Logo (from /images/logos/___.svg)
    logo: fresh-square
    sections:
    - title: User
      icon: user
      links:
      - text: Profile
        url: /
      - text: Account
        url: /
      - text: Settings
        url: /
    - title: Messages
      icon: envelope
      links:
      - text: Inbox
        url: /
      - text: Compose
        url: /
    - title: Images
      icon: image
      links:
      - text: Library
        url: /
      - text: Upload
        url: /
    - title: Settings
      icon: cog
      links:
      - text: User settings
        url: /
      - text: App settings
        url: /   
    # Footer logos (from /images/logos/clients/___.svg)
    clientlogos:
    - flu
    - Statin
    - generic
    - mm
    - cardiac
    - screening
    bulmalogo: false
    product:
    - text: Discover features
      link: /
    - text: Why choose our product?
      link: /
    - text: Compare features
      link: /
    - text: Our roadmap
      link: /
    - text: Request features
      link: /
    docs:
    - text: 
      link: /
    - text: User guides
      link: /
    - text: Admin guide
      link: /
    - text: Developers
      link: /
    blogroll:
    - text: Latest news
      link: /
    - text: Tech articles
      link: /
    - text: Video blog
      link: /
